### ISSUE TITLE
URL as a function

### ISSUE THREAD

**Issue by michaelpumo** [kbrock84/gatsby-source-fetch#1]
Thanks for this plugin, it's great. 

Is there any way to use the url option of the source plugin as a function? I believe that Gatsby allows for this.

I don't know the url ahead of time because it's on a CDN and it changes on every update.

Right now I have:

```
{
  resolve: `gatsby-source-fetch`,
  options: {
    name: `brands`,
    type: `brands`,
    url: `https://a-fixed-url.com`,
    method: `get`,
    axiosConfig: {
      headers: { Accept: "text/csv" },
    },
    saveTo: `${__dirname}/src/data/file.csv`,
    createNodes: false,
  },
}
```

But could it be something like:

```
{
  resolve: `gatsby-source-fetch`,
  options: {
    name: `brands`,
    type: `brands`,
    url: async () => {
        // Some async request...
        const url = await requestToApi()
        return url,
    },
    method: `get`,
    axiosConfig: {
      headers: { Accept: "text/csv" },
    },
    saveTo: `${__dirname}/src/data/file.csv`,
    createNodes: false,
  },
}
```

I'm not sure this is possible at all?

Many thanks for your help.

EDIT: I just created a local version for my project and implemented this feature. Would you be open to a PR for this? If so, I'll submit one.

**Comment by michaelpumo** [comment]
I just created a PR for you: https://github.com/kbrock84/gatsby-source-fetch/pull/2

Please let me know if this is suitable or if you want any changes on this.

**Comment by kbrock84** [comment]
Hey @michaelpumo thanks for the PR and sorry for the delay in review. Checking it out now.
